### ISSUE TITLE
Unable to get this running

### ISSUE THREAD

**Issue by wbashir** [spencercarli/meteor-todos-react-native-2#9]
It seems others are able to get this working but with NodeJS `v0.10.26` and `XCode 7.1`, I am running into the same error when I 'press the play button' to build the xcode project 'ReactNativeTodos' .

Error:

`TypeError: Cannot read property 'root' of null ------ DependencyResolver/crawlers/index.js:16:84`

Any ideas?

**Comment by spencercarli** [comment]
Have you tried updating watchman? `brew update && brew upgrade watchman`

**Comment by spencercarli** [comment]
Also, try the latest on master. Just updated the app to latest React Native version.

**Comment by wbashir** [comment]
Thank you very much for the update. I just pulled the latest and ran through the steps again. It failed at the last step with:

``` Javascript
const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

At this path

`meteor-todos-react-native/ReactNativeTodos/node_modules/react-native/local-cli/cli.js:56`

**Comment by zackleman** [comment]
@wbashir  That error is because the program is using an older version of Node. If you add the line 

```
. ~/.nvm/nvm.sh

```

to the top of the following file you can get around that error by forcing it to use the nvm version of node. This assumes you are using nvm.

meteor-todos-react-native-master/ReactNativeTodos/node_modules/react-native/packager/packager.sh

**Comment by wbashir** [comment]
@zleman1593 I have installed `nvm`, set up my default node version to `0.12.2` and made sure it's the only node version loaded by default. 

Updated the shell script `~/packager.sh` and added the suggested line. Looking at my `npm-debug.log` file, I am unable to confirm if the issue is with my node version or somewhere in the package.

``` Javascript

0 info it worked if it ends with ok
1 verbose cli [ '/Users/wbashir/.nvm/versions/node/v0.12.2/bin/node',
1 verbose cli   '/Users/wbashir/.nvm/versions/node/v0.12.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'ios' ]
2 info using npm@2.7.4
3 info using node@v0.12.2
4 verbose run-script [ 'preios', 'ios', 'postios' ]
5 info preios ReactNativeTodos@0.0.1
6 info ios ReactNativeTodos@0.0.1
7 verbose unsafe-perm in lifecycle true
8 info ReactNativeTodos@0.0.1 Failed to exec ios script
9 verbose stack Error: ReactNativeTodos@0.0.1 ios: `open ios/ReactNativeTodos.xcodeproj && REACT_EDITOR=atom npm start`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/Users/wbashir/.nvm/versions/node/v0.12.2/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/Users/wbashir/.nvm/versions/node/v0.12.2/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid ReactNativeTodos@0.0.1
11 verbose cwd /Users/wbashir/Documents/development/bixin/web/cloned/meteor-todos-react-native/ReactNativeTodos
12 error Darwin 14.1.0
13 error argv "/Users/wbashir/.nvm/versions/node/v0.12.2/bin/node" "/Users/wbashir/.nvm/versions/node/v0.12.2/bin/npm" "run" "ios"
14 error node v0.12.2
15 error npm  v2.7.4
16 error code ELIFECYCLE
17 error ReactNativeTodos@0.0.1 ios: `open ios/ReactNativeTodos.xcodeproj && REACT_EDITOR=atom npm start`
17 error Exit status 1
18 error Failed at the ReactNativeTodos@0.0.1 ios script 'open ios/ReactNativeTodos.xcodeproj && REACT_EDITOR=atom npm start'.
18 error This is most likely a problem with the ReactNativeTodos package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     open ios/ReactNativeTodos.xcodeproj && REACT_EDITOR=atom npm start
18 error You can get their info via:
18 error     npm owner ls ReactNativeTodos
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by wbashir** [comment]
if anyone is interested. I had to update `npm`
